language: node_js
node_js:
  - "6"
  - "8"
  - "9"
  - "10"
services: redis-server
script:
  # Install peer dependencies
  - "npm i redis@^2.6.0 @teamwork/sharedb@^1.1.4"
  - "npm run test-cover"
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
